### ISSUE TITLE
Update data overlay markdown file

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/data-files#15]
DATA_OVERLAY.md should contain info on how data contributors can validate their data files through the custom data upload user functionality before requesting the addition of new data sources.

**Comment by inghylt** [comment]
Zenhub internal error lead to this issue being created twice, #16 is the one to use

**Comment by mihai-sysbio** [comment]
which one is this then @inghylt and @nanjiangshu ?

**Comment by inghylt** [comment]
#16 IMO
